### ISSUE TITLE
Fedora 33: AttributeError: sip.enumtype object 'GridSelectionModes' has no member 'GridSelectRows'

### ISSUE THREAD

**Issue by kristofferkoch** [xesscorp/zyc#3]
* zyc version: 0.4.0
* Python version: 3.9.1
* Operating System: fedora 33

### Description

When trying to start zyc, it crashes with AttributeError

### What I Did

```
~ $ python3 -m pip install --user zyc --upgrade
Requirement already satisfied: zyc in ./.local/lib/python3.9/site-packages (0.4.0)
Requirement already satisfied: skidl>=0.0.27 in ./.local/lib/python3.9/site-packages (from zyc) (0.0.30)
Requirement already satisfied: kinparse>=0.1.0 in ./.local/lib/python3.9/site-packages (from zyc) (0.1.2)
Requirement already satisfied: pykicad in ./.local/lib/python3.9/site-packages (from zyc) (0.1.1)
Requirement already satisfied: wxpython>=4.0.7 in /usr/lib64/python3.9/site-packages (from zyc) (4.0.7)
Requirement already satisfied: pyparsing>=2.1.1 in /usr/lib/python3.9/site-packages (from kinparse>=0.1.0->zyc) (2.4.7)
Requirement already satisfied: future>=0.15.0 in ./.local/lib/python3.9/site-packages (from kinparse>=0.1.0->zyc) (0.18.2)
Requirement already satisfied: graphviz in ./.local/lib/python3.9/site-packages (from skidl>=0.0.27->zyc) (0.16)
Requirement already satisfied: pillow in /usr/lib64/python3.9/site-packages (from wxpython>=4.0.7->zyc) (7.2.0)
Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from wxpython>=4.0.7->zyc) (1.15.0)
Requirement already satisfied: numpy in ./.local/lib/python3.9/site-packages (from wxpython>=4.0.7->zyc) (1.19.4)

~ $ KICAD_SYMBOL_DIR=/usr/share/kicad/modules zyc
Traceback (most recent call last):
  File "/home/kek/.local/bin/zyc", line 8, in <module>
    sys.exit(main())
  File "/home/kek/.local/lib/python3.9/site-packages/zyc/zyc.py", line 231, in main
    AppFrame(None)
  File "/home/kek/.local/lib/python3.9/site-packages/zyc/zyc.py", line 61, in __init__
    self.panel = PartFootprintSearchPanel(self)
  File "/home/kek/.local/lib/python3.9/site-packages/zyc/zyc.py", line 211, in __init__
    add_title(PartSearchPanel(self), "Part Search", wx.TOP), wx.BOTTOM
  File "/home/kek/.local/lib/python3.9/site-packages/zyc/skidl_part_search.py", line 173, in __init__
    self.search_panel = self.InitSearchPanel(self)
  File "/home/kek/.local/lib/python3.9/site-packages/zyc/skidl_part_search.py", line 234, in InitSearchPanel
    self.found_parts = MyGrid(search_panel, ("Library", "Part"))
  File "/home/kek/.local/lib/python3.9/site-packages/zyc/common.py", line 316, in __init__
    self.SetSelectionMode(wx.grid.Grid.GridSelectionModes.GridSelectRows)
AttributeError: sip.enumtype object 'GridSelectionModes' has no member 'GridSelectRows'
```

**Comment by xesscorp** [comment]
I would try installing wxpython 4.1.1. That seems to work for me. If that solves the problem, then I'll update the setup.py file.

**Comment by squarecode** [comment]
It did in fact work! (At least for me)

Thanks
