### ISSUE TITLE
TypeError: Sizer.Add(): arguments did not match any overloaded call

### ISSUE THREAD

**Issue by thpoll83** [xesscorp/zyc#7]
* zyc version: 1.0
* Python version: 3.10.6
* Operating System: Ubuntu 22.04

### Description

Just want to start zyc

### What I Did

Installed zyc with `pip install zyc` and updated wxpython to 4.1.1 because of the issue mentioned in https://github.com/devbisme/zyc/issues/3.
Additionally installed attrdict with `pip install attrdict` as zyc failed to start because of that missing piece.

When starting, I get the following:
```
$ zyc
Traceback (most recent call last):
  File "/home/thpoll/.local/bin/zyc", line 8, in <module>
    sys.exit(main())
  File "/home/thpoll/.local/lib/python3.10/site-packages/zyc/zyc.py", line 234, in main
    AppFrame(None)
  File "/home/thpoll/.local/lib/python3.10/site-packages/zyc/zyc.py", line 62, in __init__
    self.panel = PartFootprintSearchPanel(self)
  File "/home/thpoll/.local/lib/python3.10/site-packages/zyc/zyc.py", line 212, in __init__
    add_title(PartSearchPanel(self), "Part Search", wx.TOP), wx.BOTTOM
  File "/home/thpoll/.local/lib/python3.10/site-packages/zyc/skidl_part_search.py", line 176, in __init__
    self.part_panel = self.InitPartPanel(self)
  File "/home/thpoll/.local/lib/python3.10/site-packages/zyc/skidl_part_search.py", line 280, in InitPartPanel
    self.part_desc = Description(part_panel, "Part Description/Tags")
  File "/home/thpoll/.local/lib/python3.10/site-packages/zyc/common.py", line 176, in __init__
    vbox.Add(
TypeError: Sizer.Add(): arguments did not match any overloaded call:
  overload 1: 'proportion' is not a valid keyword argument
  overload 2: argument 'border' has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'StaticText'
  overload 4: argument 1 has unexpected type 'StaticText'
  overload 5: argument 1 has unexpected type 'StaticText'
  overload 6: argument 1 has unexpected type 'StaticText'
  overload 7: argument 1 has unexpected type 'StaticText'
  overload 8: argument 1 has unexpected type 'StaticText'
  overload 9: argument 1 has unexpected type 'StaticText'

```

**Comment by devbisme** [comment]
Thanks for the error report! I replicated the problem and made some corrections. You can install the updated version like this:
```bash
pip install git+https://github.com/devbisme/zyc@dev
```

**Comment by thpoll83** [comment]
Thanks it is starting now. However, when selecting a part in the list nothing happens and I can see the following error on the console:
`Traceback (most recent call last):
  File "/home/thpoll/.local/lib/python3.10/site-packages/zyc/skidl_part_search.py", line 376, in OnSelectCell
    part.parse()  # Instantiate pins.
  File "/home/thpoll/.local/lib/python3.10/site-packages/skidl/part.py", line 373, in parse
    parse_func(get_name_only)
  File "/home/thpoll/.local/lib/python3.10/site-packages/skidl/tools/kicad/kicad.py", line 297, in parse_lib_part
    _parse_lib_part_kicad_v6(self, get_name_only)
  File "/home/thpoll/.local/lib/python3.10/site-packages/skidl/tools/kicad/kicad.py", line 817, in _parse_lib_part_kicad_v6
    self.ref_prefix = self.fields["F0"]  # Part ref prefix (e.g., 'R').
KeyError: 'F0'
`

Could that be related to Kicad7 ?

**Comment by devbisme** [comment]
Make sure you set the search path to where your symbols and footprints are stored. Zyc works with V5 and V6 format, so it should work with V7 (I heard the library changes were minor).

I found a few other errors, so you should load the development versions of zyc and skidl:
```bash
pip install git+https://github.com/devbisme/zyc@dev
pip install git+https://github.com/devbisme/skidl@development
```

**Comment by thpoll83** [comment]
Thanks for the help and sorry for the late reply, somehow I missed that.

So I just updated, but get a new error. I guess skidl is maybe too 'new" and changed somehow:
`$ zyc
Traceback (most recent call last):
  File "/home/thpoll/.local/bin/zyc", line 5, in <module>
    from zyc.zyc import main
  File "/home/thpoll/.local/lib/python3.10/site-packages/zyc/__init__.py", line 5, in <module>
    from .zyc import *
  File "/home/thpoll/.local/lib/python3.10/site-packages/zyc/zyc.py", line 35, in <module>
    from skidl import (
ImportError: cannot import name 'footprint_cache' from 'skidl' (/home/thpoll/.local/lib/python3.10/site-packages/skidl/__init__.py)`
