### ISSUE TITLE
problem on running zyc with ubuntu 22.04

### ISSUE THREAD

**Issue by smzahraee** [xesscorp/zyc#9]
* zyc version:
* Python version: 3.11.5
* Operating System: ubuntu 22.04 LTS

### Description

problem on running zyc 

### What I Did

```
zyc
```
 I got

```
WARNING: KICAD7_SYMBOL_DIR environment variable is missing, so the default KiCad symbol libraries won't be searched. @ [/media/user/projects/projects/test2/<frozen importlib._bootstrap_external>:940=>/media/user/projects/projects/test2/<frozen importlib._bootstrap>:241]
WARNING: KICAD8_SYMBOL_DIR environment variable is missing, so the default KiCad symbol libraries won't be searched. @ [/media/user/projects/projects/test2/<frozen importlib._bootstrap_external>:940=>/media/user/projects/projects/test2/<frozen importlib._bootstrap>:241]
Traceback (most recent call last):
  File "/media/user/projects/anaconda3/bin/zyc", line 5, in <module>
    from zyc.zyc import main
  File "/media/user/projects/anaconda3/lib/python3.11/site-packages/zyc/__init__.py", line 5, in <module>
    from .zyc import *
  File "/media/user/projects/anaconda3/lib/python3.11/site-packages/zyc/zyc.py", line 35, in <module>
    from skidl import (
ImportError: cannot import name 'footprint_cache' from 'skidl' (/media/user/projects/anaconda3/lib/python3.11/site-packages/skidl/__init__.py)
(base)
```

**Comment by joshua-dean** [comment]
Encountered a similar issue when trying to set up the tool today, where a handful of `skidl` imports don't resolve correctly.

My guess is [this `skidl` commit](https://github.com/devbisme/skidl/commit/e7c13b28910d1f0c62f175eb1d2e540f07105ac1) is the culprit, narrowing a bunch of wildcard imports down to specific ones. `zyc` hasn't been updated since that change.

I was able to get basic functionality by installing v1.1.0:
```bash
pip install skidl==1.1.0
```
and changing the relative imports in `zyc.py`, `skidl_footprint_search.py`, and `skidl_part_search.py` to be absolute (drop the leading '.'). 
The latter fix might only be necessary for my environment setup: an isolated conda environment and launching the GUI from vscode. I did not get the `zyc` command line executable to work in any context.

Although this allowed searching to work, actual parsing of the part files still failed, which might have to do with me using KiCAD8.
